// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ad_log.proto

package com.lixl.stream.entity;

public interface AdLogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.AdLog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string request_id = 1;</code>
   */
  java.lang.String getRequestId();
  /**
   * <code>optional string request_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>optional uint64 timestamp = 2;</code>
   */
  long getTimestamp();

  /**
   * <code>optional .grpc.ProcessInfo process_info = 3;</code>
   */
  boolean hasProcessInfo();
  /**
   * <code>optional .grpc.ProcessInfo process_info = 3;</code>
   */
  com.lixl.stream.entity.ProcessInfo getProcessInfo();
  /**
   * <code>optional .grpc.ProcessInfo process_info = 3;</code>
   */
  com.lixl.stream.entity.ProcessInfoOrBuilder getProcessInfoOrBuilder();

  /**
   * <code>optional string device_id = 11;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <code>optional string device_id = 11;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>optional string os = 12;</code>
   */
  java.lang.String getOs();
  /**
   * <code>optional string os = 12;</code>
   */
  com.google.protobuf.ByteString
      getOsBytes();

  /**
   * <code>optional string network = 13;</code>
   */
  java.lang.String getNetwork();
  /**
   * <code>optional string network = 13;</code>
   */
  com.google.protobuf.ByteString
      getNetworkBytes();

  /**
   * <pre>
   * dmp info
   * </pre>
   *
   * <code>optional string user_id = 51;</code>
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * dmp info
   * </pre>
   *
   * <code>optional string user_id = 51;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>optional string gender = 52;</code>
   */
  java.lang.String getGender();
  /**
   * <code>optional string gender = 52;</code>
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>optional int32 age = 53;</code>
   */
  int getAge();

  /**
   * <code>optional string country = 54;</code>
   */
  java.lang.String getCountry();
  /**
   * <code>optional string country = 54;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>optional string province = 55;</code>
   */
  java.lang.String getProvince();
  /**
   * <code>optional string province = 55;</code>
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <code>optional string city = 56;</code>
   */
  java.lang.String getCity();
  /**
   * <code>optional string city = 56;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <pre>
   * ad info 竞价胜出的广告信息  （100-199）
   * </pre>
   *
   * <code>optional string source_type = 100;</code>
   */
  java.lang.String getSourceType();
  /**
   * <pre>
   * ad info 竞价胜出的广告信息  （100-199）
   * </pre>
   *
   * <code>optional string source_type = 100;</code>
   */
  com.google.protobuf.ByteString
      getSourceTypeBytes();

  /**
   * <code>optional string bid_type = 101;</code>
   */
  java.lang.String getBidType();
  /**
   * <code>optional string bid_type = 101;</code>
   */
  com.google.protobuf.ByteString
      getBidTypeBytes();

  /**
   * <pre>
   *出价
   * </pre>
   *
   * <code>optional int64 bid_price = 102;</code>
   */
  long getBidPrice();

  /**
   * <pre>
   *广告位置
   * </pre>
   *
   * <code>optional int64 pos_id = 150;</code>
   */
  long getPosId();

  /**
   * <pre>
   *广告主
   * </pre>
   *
   * <code>optional int64 account_id = 151;</code>
   */
  long getAccountId();

  /**
   * <pre>
   *广告单元
   * </pre>
   *
   * <code>optional int64 unit_id = 152;</code>
   */
  long getUnitId();

  /**
   * <pre>
   *广告创意
   * </pre>
   *
   * <code>optional int64 creative_id = 153;</code>
   */
  long getCreativeId();

  /**
   * <pre>
   * event
   * </pre>
   *
   * <code>optional string event_type = 200;</code>
   */
  java.lang.String getEventType();
  /**
   * <pre>
   * event
   * </pre>
   *
   * <code>optional string event_type = 200;</code>
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();

  /**
   * <pre>
   *广告下发了
   * </pre>
   *
   * <code>optional int64 send = 201;</code>
   */
  long getSend();

  /**
   * <pre>
   *广告曝光了
   * </pre>
   *
   * <code>optional int64 impression = 202;</code>
   */
  long getImpression();

  /**
   * <pre>
   *广告点击了
   * </pre>
   *
   * <code>optional int64 click = 203;</code>
   */
  long getClick();

  /**
   * <pre>
   *广告点击了
   * </pre>
   *
   * <code>optional int64 download = 204;</code>
   */
  long getDownload();

  /**
   * <pre>
   *广告安装了
   * </pre>
   *
   * <code>optional int64 installed = 205;</code>
   */
  long getInstalled();

  /**
   * <pre>
   *广告支付了
   * </pre>
   *
   * <code>optional int64 pay = 206;</code>
   */
  long getPay();
}
