// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ad_log.proto

package com.lixl.stream.entity;

/**
 * Protobuf type {@code grpc.AdLog}
 */
public  final class AdLog extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.AdLog)
    AdLogOrBuilder {
  // Use AdLog.newBuilder() to construct.
  private AdLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdLog() {
    requestId_ = "";
    timestamp_ = 0L;
    deviceId_ = "";
    os_ = "";
    network_ = "";
    userId_ = "";
    gender_ = "";
    age_ = 0;
    country_ = "";
    province_ = "";
    city_ = "";
    sourceType_ = "";
    bidType_ = "";
    bidPrice_ = 0L;
    posId_ = 0L;
    accountId_ = 0L;
    unitId_ = 0L;
    creativeId_ = 0L;
    eventType_ = "";
    send_ = 0L;
    impression_ = 0L;
    click_ = 0L;
    download_ = 0L;
    installed_ = 0L;
    pay_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private AdLog(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            requestId_ = s;
            break;
          }
          case 16: {

            timestamp_ = input.readUInt64();
            break;
          }
          case 26: {
            com.lixl.stream.entity.ProcessInfo.Builder subBuilder = null;
            if (processInfo_ != null) {
              subBuilder = processInfo_.toBuilder();
            }
            processInfo_ = input.readMessage(com.lixl.stream.entity.ProcessInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(processInfo_);
              processInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceId_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            os_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            network_ = s;
            break;
          }
          case 410: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 418: {
            java.lang.String s = input.readStringRequireUtf8();

            gender_ = s;
            break;
          }
          case 424: {

            age_ = input.readInt32();
            break;
          }
          case 434: {
            java.lang.String s = input.readStringRequireUtf8();

            country_ = s;
            break;
          }
          case 442: {
            java.lang.String s = input.readStringRequireUtf8();

            province_ = s;
            break;
          }
          case 450: {
            java.lang.String s = input.readStringRequireUtf8();

            city_ = s;
            break;
          }
          case 802: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceType_ = s;
            break;
          }
          case 810: {
            java.lang.String s = input.readStringRequireUtf8();

            bidType_ = s;
            break;
          }
          case 816: {

            bidPrice_ = input.readInt64();
            break;
          }
          case 1200: {

            posId_ = input.readInt64();
            break;
          }
          case 1208: {

            accountId_ = input.readInt64();
            break;
          }
          case 1216: {

            unitId_ = input.readInt64();
            break;
          }
          case 1224: {

            creativeId_ = input.readInt64();
            break;
          }
          case 1602: {
            java.lang.String s = input.readStringRequireUtf8();

            eventType_ = s;
            break;
          }
          case 1608: {

            send_ = input.readInt64();
            break;
          }
          case 1616: {

            impression_ = input.readInt64();
            break;
          }
          case 1624: {

            click_ = input.readInt64();
            break;
          }
          case 1632: {

            download_ = input.readInt64();
            break;
          }
          case 1640: {

            installed_ = input.readInt64();
            break;
          }
          case 1648: {

            pay_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lixl.stream.entity.AdLogProto.internal_static_grpc_AdLog_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lixl.stream.entity.AdLogProto.internal_static_grpc_AdLog_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lixl.stream.entity.AdLog.class, com.lixl.stream.entity.AdLog.Builder.class);
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object requestId_;
  /**
   * <code>optional string request_id = 1;</code>
   */
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string request_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_;
  /**
   * <code>optional uint64 timestamp = 2;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int PROCESS_INFO_FIELD_NUMBER = 3;
  private com.lixl.stream.entity.ProcessInfo processInfo_;
  /**
   * <code>optional .grpc.ProcessInfo process_info = 3;</code>
   */
  public boolean hasProcessInfo() {
    return processInfo_ != null;
  }
  /**
   * <code>optional .grpc.ProcessInfo process_info = 3;</code>
   */
  public com.lixl.stream.entity.ProcessInfo getProcessInfo() {
    return processInfo_ == null ? com.lixl.stream.entity.ProcessInfo.getDefaultInstance() : processInfo_;
  }
  /**
   * <code>optional .grpc.ProcessInfo process_info = 3;</code>
   */
  public com.lixl.stream.entity.ProcessInfoOrBuilder getProcessInfoOrBuilder() {
    return getProcessInfo();
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 11;
  private volatile java.lang.Object deviceId_;
  /**
   * <code>optional string device_id = 11;</code>
   */
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string device_id = 11;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OS_FIELD_NUMBER = 12;
  private volatile java.lang.Object os_;
  /**
   * <code>optional string os = 12;</code>
   */
  public java.lang.String getOs() {
    java.lang.Object ref = os_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      os_ = s;
      return s;
    }
  }
  /**
   * <code>optional string os = 12;</code>
   */
  public com.google.protobuf.ByteString
      getOsBytes() {
    java.lang.Object ref = os_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      os_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NETWORK_FIELD_NUMBER = 13;
  private volatile java.lang.Object network_;
  /**
   * <code>optional string network = 13;</code>
   */
  public java.lang.String getNetwork() {
    java.lang.Object ref = network_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      network_ = s;
      return s;
    }
  }
  /**
   * <code>optional string network = 13;</code>
   */
  public com.google.protobuf.ByteString
      getNetworkBytes() {
    java.lang.Object ref = network_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      network_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_FIELD_NUMBER = 51;
  private volatile java.lang.Object userId_;
  /**
   * <pre>
   * dmp info
   * </pre>
   *
   * <code>optional string user_id = 51;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * dmp info
   * </pre>
   *
   * <code>optional string user_id = 51;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENDER_FIELD_NUMBER = 52;
  private volatile java.lang.Object gender_;
  /**
   * <code>optional string gender = 52;</code>
   */
  public java.lang.String getGender() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gender_ = s;
      return s;
    }
  }
  /**
   * <code>optional string gender = 52;</code>
   */
  public com.google.protobuf.ByteString
      getGenderBytes() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 53;
  private int age_;
  /**
   * <code>optional int32 age = 53;</code>
   */
  public int getAge() {
    return age_;
  }

  public static final int COUNTRY_FIELD_NUMBER = 54;
  private volatile java.lang.Object country_;
  /**
   * <code>optional string country = 54;</code>
   */
  public java.lang.String getCountry() {
    java.lang.Object ref = country_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      country_ = s;
      return s;
    }
  }
  /**
   * <code>optional string country = 54;</code>
   */
  public com.google.protobuf.ByteString
      getCountryBytes() {
    java.lang.Object ref = country_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      country_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROVINCE_FIELD_NUMBER = 55;
  private volatile java.lang.Object province_;
  /**
   * <code>optional string province = 55;</code>
   */
  public java.lang.String getProvince() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      province_ = s;
      return s;
    }
  }
  /**
   * <code>optional string province = 55;</code>
   */
  public com.google.protobuf.ByteString
      getProvinceBytes() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      province_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CITY_FIELD_NUMBER = 56;
  private volatile java.lang.Object city_;
  /**
   * <code>optional string city = 56;</code>
   */
  public java.lang.String getCity() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      city_ = s;
      return s;
    }
  }
  /**
   * <code>optional string city = 56;</code>
   */
  public com.google.protobuf.ByteString
      getCityBytes() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      city_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_TYPE_FIELD_NUMBER = 100;
  private volatile java.lang.Object sourceType_;
  /**
   * <pre>
   * ad info 竞价胜出的广告信息  （100-199）
   * </pre>
   *
   * <code>optional string source_type = 100;</code>
   */
  public java.lang.String getSourceType() {
    java.lang.Object ref = sourceType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ad info 竞价胜出的广告信息  （100-199）
   * </pre>
   *
   * <code>optional string source_type = 100;</code>
   */
  public com.google.protobuf.ByteString
      getSourceTypeBytes() {
    java.lang.Object ref = sourceType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BID_TYPE_FIELD_NUMBER = 101;
  private volatile java.lang.Object bidType_;
  /**
   * <code>optional string bid_type = 101;</code>
   */
  public java.lang.String getBidType() {
    java.lang.Object ref = bidType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bidType_ = s;
      return s;
    }
  }
  /**
   * <code>optional string bid_type = 101;</code>
   */
  public com.google.protobuf.ByteString
      getBidTypeBytes() {
    java.lang.Object ref = bidType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bidType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BID_PRICE_FIELD_NUMBER = 102;
  private long bidPrice_;
  /**
   * <pre>
   *出价
   * </pre>
   *
   * <code>optional int64 bid_price = 102;</code>
   */
  public long getBidPrice() {
    return bidPrice_;
  }

  public static final int POS_ID_FIELD_NUMBER = 150;
  private long posId_;
  /**
   * <pre>
   *广告位置
   * </pre>
   *
   * <code>optional int64 pos_id = 150;</code>
   */
  public long getPosId() {
    return posId_;
  }

  public static final int ACCOUNT_ID_FIELD_NUMBER = 151;
  private long accountId_;
  /**
   * <pre>
   *广告主
   * </pre>
   *
   * <code>optional int64 account_id = 151;</code>
   */
  public long getAccountId() {
    return accountId_;
  }

  public static final int UNIT_ID_FIELD_NUMBER = 152;
  private long unitId_;
  /**
   * <pre>
   *广告单元
   * </pre>
   *
   * <code>optional int64 unit_id = 152;</code>
   */
  public long getUnitId() {
    return unitId_;
  }

  public static final int CREATIVE_ID_FIELD_NUMBER = 153;
  private long creativeId_;
  /**
   * <pre>
   *广告创意
   * </pre>
   *
   * <code>optional int64 creative_id = 153;</code>
   */
  public long getCreativeId() {
    return creativeId_;
  }

  public static final int EVENT_TYPE_FIELD_NUMBER = 200;
  private volatile java.lang.Object eventType_;
  /**
   * <pre>
   * event
   * </pre>
   *
   * <code>optional string event_type = 200;</code>
   */
  public java.lang.String getEventType() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * event
   * </pre>
   *
   * <code>optional string event_type = 200;</code>
   */
  public com.google.protobuf.ByteString
      getEventTypeBytes() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEND_FIELD_NUMBER = 201;
  private long send_;
  /**
   * <pre>
   *广告下发了
   * </pre>
   *
   * <code>optional int64 send = 201;</code>
   */
  public long getSend() {
    return send_;
  }

  public static final int IMPRESSION_FIELD_NUMBER = 202;
  private long impression_;
  /**
   * <pre>
   *广告曝光了
   * </pre>
   *
   * <code>optional int64 impression = 202;</code>
   */
  public long getImpression() {
    return impression_;
  }

  public static final int CLICK_FIELD_NUMBER = 203;
  private long click_;
  /**
   * <pre>
   *广告点击了
   * </pre>
   *
   * <code>optional int64 click = 203;</code>
   */
  public long getClick() {
    return click_;
  }

  public static final int DOWNLOAD_FIELD_NUMBER = 204;
  private long download_;
  /**
   * <pre>
   *广告点击了
   * </pre>
   *
   * <code>optional int64 download = 204;</code>
   */
  public long getDownload() {
    return download_;
  }

  public static final int INSTALLED_FIELD_NUMBER = 205;
  private long installed_;
  /**
   * <pre>
   *广告安装了
   * </pre>
   *
   * <code>optional int64 installed = 205;</code>
   */
  public long getInstalled() {
    return installed_;
  }

  public static final int PAY_FIELD_NUMBER = 206;
  private long pay_;
  /**
   * <pre>
   *广告支付了
   * </pre>
   *
   * <code>optional int64 pay = 206;</code>
   */
  public long getPay() {
    return pay_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRequestIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
    }
    if (timestamp_ != 0L) {
      output.writeUInt64(2, timestamp_);
    }
    if (processInfo_ != null) {
      output.writeMessage(3, getProcessInfo());
    }
    if (!getDeviceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, deviceId_);
    }
    if (!getOsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, os_);
    }
    if (!getNetworkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, network_);
    }
    if (!getUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 51, userId_);
    }
    if (!getGenderBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 52, gender_);
    }
    if (age_ != 0) {
      output.writeInt32(53, age_);
    }
    if (!getCountryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 54, country_);
    }
    if (!getProvinceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 55, province_);
    }
    if (!getCityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 56, city_);
    }
    if (!getSourceTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 100, sourceType_);
    }
    if (!getBidTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 101, bidType_);
    }
    if (bidPrice_ != 0L) {
      output.writeInt64(102, bidPrice_);
    }
    if (posId_ != 0L) {
      output.writeInt64(150, posId_);
    }
    if (accountId_ != 0L) {
      output.writeInt64(151, accountId_);
    }
    if (unitId_ != 0L) {
      output.writeInt64(152, unitId_);
    }
    if (creativeId_ != 0L) {
      output.writeInt64(153, creativeId_);
    }
    if (!getEventTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 200, eventType_);
    }
    if (send_ != 0L) {
      output.writeInt64(201, send_);
    }
    if (impression_ != 0L) {
      output.writeInt64(202, impression_);
    }
    if (click_ != 0L) {
      output.writeInt64(203, click_);
    }
    if (download_ != 0L) {
      output.writeInt64(204, download_);
    }
    if (installed_ != 0L) {
      output.writeInt64(205, installed_);
    }
    if (pay_ != 0L) {
      output.writeInt64(206, pay_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRequestIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, timestamp_);
    }
    if (processInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getProcessInfo());
    }
    if (!getDeviceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, deviceId_);
    }
    if (!getOsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, os_);
    }
    if (!getNetworkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, network_);
    }
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(51, userId_);
    }
    if (!getGenderBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(52, gender_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(53, age_);
    }
    if (!getCountryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(54, country_);
    }
    if (!getProvinceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(55, province_);
    }
    if (!getCityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(56, city_);
    }
    if (!getSourceTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(100, sourceType_);
    }
    if (!getBidTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(101, bidType_);
    }
    if (bidPrice_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(102, bidPrice_);
    }
    if (posId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(150, posId_);
    }
    if (accountId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(151, accountId_);
    }
    if (unitId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(152, unitId_);
    }
    if (creativeId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(153, creativeId_);
    }
    if (!getEventTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(200, eventType_);
    }
    if (send_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(201, send_);
    }
    if (impression_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(202, impression_);
    }
    if (click_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(203, click_);
    }
    if (download_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(204, download_);
    }
    if (installed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(205, installed_);
    }
    if (pay_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(206, pay_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lixl.stream.entity.AdLog)) {
      return super.equals(obj);
    }
    com.lixl.stream.entity.AdLog other = (com.lixl.stream.entity.AdLog) obj;

    boolean result = true;
    result = result && getRequestId()
        .equals(other.getRequestId());
    result = result && (getTimestamp()
        == other.getTimestamp());
    result = result && (hasProcessInfo() == other.hasProcessInfo());
    if (hasProcessInfo()) {
      result = result && getProcessInfo()
          .equals(other.getProcessInfo());
    }
    result = result && getDeviceId()
        .equals(other.getDeviceId());
    result = result && getOs()
        .equals(other.getOs());
    result = result && getNetwork()
        .equals(other.getNetwork());
    result = result && getUserId()
        .equals(other.getUserId());
    result = result && getGender()
        .equals(other.getGender());
    result = result && (getAge()
        == other.getAge());
    result = result && getCountry()
        .equals(other.getCountry());
    result = result && getProvince()
        .equals(other.getProvince());
    result = result && getCity()
        .equals(other.getCity());
    result = result && getSourceType()
        .equals(other.getSourceType());
    result = result && getBidType()
        .equals(other.getBidType());
    result = result && (getBidPrice()
        == other.getBidPrice());
    result = result && (getPosId()
        == other.getPosId());
    result = result && (getAccountId()
        == other.getAccountId());
    result = result && (getUnitId()
        == other.getUnitId());
    result = result && (getCreativeId()
        == other.getCreativeId());
    result = result && getEventType()
        .equals(other.getEventType());
    result = result && (getSend()
        == other.getSend());
    result = result && (getImpression()
        == other.getImpression());
    result = result && (getClick()
        == other.getClick());
    result = result && (getDownload()
        == other.getDownload());
    result = result && (getInstalled()
        == other.getInstalled());
    result = result && (getPay()
        == other.getPay());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    if (hasProcessInfo()) {
      hash = (37 * hash) + PROCESS_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getProcessInfo().hashCode();
    }
    hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (37 * hash) + OS_FIELD_NUMBER;
    hash = (53 * hash) + getOs().hashCode();
    hash = (37 * hash) + NETWORK_FIELD_NUMBER;
    hash = (53 * hash) + getNetwork().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + GENDER_FIELD_NUMBER;
    hash = (53 * hash) + getGender().hashCode();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
    hash = (53 * hash) + getCountry().hashCode();
    hash = (37 * hash) + PROVINCE_FIELD_NUMBER;
    hash = (53 * hash) + getProvince().hashCode();
    hash = (37 * hash) + CITY_FIELD_NUMBER;
    hash = (53 * hash) + getCity().hashCode();
    hash = (37 * hash) + SOURCE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSourceType().hashCode();
    hash = (37 * hash) + BID_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getBidType().hashCode();
    hash = (37 * hash) + BID_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBidPrice());
    hash = (37 * hash) + POS_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPosId());
    hash = (37 * hash) + ACCOUNT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAccountId());
    hash = (37 * hash) + UNIT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUnitId());
    hash = (37 * hash) + CREATIVE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreativeId());
    hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEventType().hashCode();
    hash = (37 * hash) + SEND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSend());
    hash = (37 * hash) + IMPRESSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getImpression());
    hash = (37 * hash) + CLICK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getClick());
    hash = (37 * hash) + DOWNLOAD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDownload());
    hash = (37 * hash) + INSTALLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInstalled());
    hash = (37 * hash) + PAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPay());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lixl.stream.entity.AdLog parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lixl.stream.entity.AdLog parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lixl.stream.entity.AdLog parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lixl.stream.entity.AdLog parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lixl.stream.entity.AdLog parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lixl.stream.entity.AdLog parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lixl.stream.entity.AdLog parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lixl.stream.entity.AdLog parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lixl.stream.entity.AdLog parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lixl.stream.entity.AdLog parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lixl.stream.entity.AdLog prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.AdLog}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.AdLog)
      com.lixl.stream.entity.AdLogOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lixl.stream.entity.AdLogProto.internal_static_grpc_AdLog_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lixl.stream.entity.AdLogProto.internal_static_grpc_AdLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lixl.stream.entity.AdLog.class, com.lixl.stream.entity.AdLog.Builder.class);
    }

    // Construct using com.lixl.stream.entity.AdLog.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      requestId_ = "";

      timestamp_ = 0L;

      if (processInfoBuilder_ == null) {
        processInfo_ = null;
      } else {
        processInfo_ = null;
        processInfoBuilder_ = null;
      }
      deviceId_ = "";

      os_ = "";

      network_ = "";

      userId_ = "";

      gender_ = "";

      age_ = 0;

      country_ = "";

      province_ = "";

      city_ = "";

      sourceType_ = "";

      bidType_ = "";

      bidPrice_ = 0L;

      posId_ = 0L;

      accountId_ = 0L;

      unitId_ = 0L;

      creativeId_ = 0L;

      eventType_ = "";

      send_ = 0L;

      impression_ = 0L;

      click_ = 0L;

      download_ = 0L;

      installed_ = 0L;

      pay_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lixl.stream.entity.AdLogProto.internal_static_grpc_AdLog_descriptor;
    }

    public com.lixl.stream.entity.AdLog getDefaultInstanceForType() {
      return com.lixl.stream.entity.AdLog.getDefaultInstance();
    }

    public com.lixl.stream.entity.AdLog build() {
      com.lixl.stream.entity.AdLog result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lixl.stream.entity.AdLog buildPartial() {
      com.lixl.stream.entity.AdLog result = new com.lixl.stream.entity.AdLog(this);
      result.requestId_ = requestId_;
      result.timestamp_ = timestamp_;
      if (processInfoBuilder_ == null) {
        result.processInfo_ = processInfo_;
      } else {
        result.processInfo_ = processInfoBuilder_.build();
      }
      result.deviceId_ = deviceId_;
      result.os_ = os_;
      result.network_ = network_;
      result.userId_ = userId_;
      result.gender_ = gender_;
      result.age_ = age_;
      result.country_ = country_;
      result.province_ = province_;
      result.city_ = city_;
      result.sourceType_ = sourceType_;
      result.bidType_ = bidType_;
      result.bidPrice_ = bidPrice_;
      result.posId_ = posId_;
      result.accountId_ = accountId_;
      result.unitId_ = unitId_;
      result.creativeId_ = creativeId_;
      result.eventType_ = eventType_;
      result.send_ = send_;
      result.impression_ = impression_;
      result.click_ = click_;
      result.download_ = download_;
      result.installed_ = installed_;
      result.pay_ = pay_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lixl.stream.entity.AdLog) {
        return mergeFrom((com.lixl.stream.entity.AdLog)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lixl.stream.entity.AdLog other) {
      if (other == com.lixl.stream.entity.AdLog.getDefaultInstance()) return this;
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.hasProcessInfo()) {
        mergeProcessInfo(other.getProcessInfo());
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        onChanged();
      }
      if (!other.getOs().isEmpty()) {
        os_ = other.os_;
        onChanged();
      }
      if (!other.getNetwork().isEmpty()) {
        network_ = other.network_;
        onChanged();
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (!other.getGender().isEmpty()) {
        gender_ = other.gender_;
        onChanged();
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (!other.getCountry().isEmpty()) {
        country_ = other.country_;
        onChanged();
      }
      if (!other.getProvince().isEmpty()) {
        province_ = other.province_;
        onChanged();
      }
      if (!other.getCity().isEmpty()) {
        city_ = other.city_;
        onChanged();
      }
      if (!other.getSourceType().isEmpty()) {
        sourceType_ = other.sourceType_;
        onChanged();
      }
      if (!other.getBidType().isEmpty()) {
        bidType_ = other.bidType_;
        onChanged();
      }
      if (other.getBidPrice() != 0L) {
        setBidPrice(other.getBidPrice());
      }
      if (other.getPosId() != 0L) {
        setPosId(other.getPosId());
      }
      if (other.getAccountId() != 0L) {
        setAccountId(other.getAccountId());
      }
      if (other.getUnitId() != 0L) {
        setUnitId(other.getUnitId());
      }
      if (other.getCreativeId() != 0L) {
        setCreativeId(other.getCreativeId());
      }
      if (!other.getEventType().isEmpty()) {
        eventType_ = other.eventType_;
        onChanged();
      }
      if (other.getSend() != 0L) {
        setSend(other.getSend());
      }
      if (other.getImpression() != 0L) {
        setImpression(other.getImpression());
      }
      if (other.getClick() != 0L) {
        setClick(other.getClick());
      }
      if (other.getDownload() != 0L) {
        setDownload(other.getDownload());
      }
      if (other.getInstalled() != 0L) {
        setInstalled(other.getInstalled());
      }
      if (other.getPay() != 0L) {
        setPay(other.getPay());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lixl.stream.entity.AdLog parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lixl.stream.entity.AdLog) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object requestId_ = "";
    /**
     * <code>optional string request_id = 1;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string request_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string request_id = 1;</code>
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string request_id = 1;</code>
     */
    public Builder clearRequestId() {
      
      requestId_ = getDefaultInstance().getRequestId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string request_id = 1;</code>
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestId_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>optional uint64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>optional uint64 timestamp = 2;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 timestamp = 2;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private com.lixl.stream.entity.ProcessInfo processInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lixl.stream.entity.ProcessInfo, com.lixl.stream.entity.ProcessInfo.Builder, com.lixl.stream.entity.ProcessInfoOrBuilder> processInfoBuilder_;
    /**
     * <code>optional .grpc.ProcessInfo process_info = 3;</code>
     */
    public boolean hasProcessInfo() {
      return processInfoBuilder_ != null || processInfo_ != null;
    }
    /**
     * <code>optional .grpc.ProcessInfo process_info = 3;</code>
     */
    public com.lixl.stream.entity.ProcessInfo getProcessInfo() {
      if (processInfoBuilder_ == null) {
        return processInfo_ == null ? com.lixl.stream.entity.ProcessInfo.getDefaultInstance() : processInfo_;
      } else {
        return processInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .grpc.ProcessInfo process_info = 3;</code>
     */
    public Builder setProcessInfo(com.lixl.stream.entity.ProcessInfo value) {
      if (processInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        processInfo_ = value;
        onChanged();
      } else {
        processInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .grpc.ProcessInfo process_info = 3;</code>
     */
    public Builder setProcessInfo(
        com.lixl.stream.entity.ProcessInfo.Builder builderForValue) {
      if (processInfoBuilder_ == null) {
        processInfo_ = builderForValue.build();
        onChanged();
      } else {
        processInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .grpc.ProcessInfo process_info = 3;</code>
     */
    public Builder mergeProcessInfo(com.lixl.stream.entity.ProcessInfo value) {
      if (processInfoBuilder_ == null) {
        if (processInfo_ != null) {
          processInfo_ =
            com.lixl.stream.entity.ProcessInfo.newBuilder(processInfo_).mergeFrom(value).buildPartial();
        } else {
          processInfo_ = value;
        }
        onChanged();
      } else {
        processInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .grpc.ProcessInfo process_info = 3;</code>
     */
    public Builder clearProcessInfo() {
      if (processInfoBuilder_ == null) {
        processInfo_ = null;
        onChanged();
      } else {
        processInfo_ = null;
        processInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .grpc.ProcessInfo process_info = 3;</code>
     */
    public com.lixl.stream.entity.ProcessInfo.Builder getProcessInfoBuilder() {
      
      onChanged();
      return getProcessInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .grpc.ProcessInfo process_info = 3;</code>
     */
    public com.lixl.stream.entity.ProcessInfoOrBuilder getProcessInfoOrBuilder() {
      if (processInfoBuilder_ != null) {
        return processInfoBuilder_.getMessageOrBuilder();
      } else {
        return processInfo_ == null ?
            com.lixl.stream.entity.ProcessInfo.getDefaultInstance() : processInfo_;
      }
    }
    /**
     * <code>optional .grpc.ProcessInfo process_info = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lixl.stream.entity.ProcessInfo, com.lixl.stream.entity.ProcessInfo.Builder, com.lixl.stream.entity.ProcessInfoOrBuilder> 
        getProcessInfoFieldBuilder() {
      if (processInfoBuilder_ == null) {
        processInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.lixl.stream.entity.ProcessInfo, com.lixl.stream.entity.ProcessInfo.Builder, com.lixl.stream.entity.ProcessInfoOrBuilder>(
                getProcessInfo(),
                getParentForChildren(),
                isClean());
        processInfo_ = null;
      }
      return processInfoBuilder_;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <code>optional string device_id = 11;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string device_id = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string device_id = 11;</code>
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string device_id = 11;</code>
     */
    public Builder clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string device_id = 11;</code>
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object os_ = "";
    /**
     * <code>optional string os = 12;</code>
     */
    public java.lang.String getOs() {
      java.lang.Object ref = os_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        os_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string os = 12;</code>
     */
    public com.google.protobuf.ByteString
        getOsBytes() {
      java.lang.Object ref = os_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        os_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string os = 12;</code>
     */
    public Builder setOs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      os_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string os = 12;</code>
     */
    public Builder clearOs() {
      
      os_ = getDefaultInstance().getOs();
      onChanged();
      return this;
    }
    /**
     * <code>optional string os = 12;</code>
     */
    public Builder setOsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      os_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object network_ = "";
    /**
     * <code>optional string network = 13;</code>
     */
    public java.lang.String getNetwork() {
      java.lang.Object ref = network_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        network_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string network = 13;</code>
     */
    public com.google.protobuf.ByteString
        getNetworkBytes() {
      java.lang.Object ref = network_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        network_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string network = 13;</code>
     */
    public Builder setNetwork(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      network_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string network = 13;</code>
     */
    public Builder clearNetwork() {
      
      network_ = getDefaultInstance().getNetwork();
      onChanged();
      return this;
    }
    /**
     * <code>optional string network = 13;</code>
     */
    public Builder setNetworkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      network_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <pre>
     * dmp info
     * </pre>
     *
     * <code>optional string user_id = 51;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * dmp info
     * </pre>
     *
     * <code>optional string user_id = 51;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * dmp info
     * </pre>
     *
     * <code>optional string user_id = 51;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * dmp info
     * </pre>
     *
     * <code>optional string user_id = 51;</code>
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * dmp info
     * </pre>
     *
     * <code>optional string user_id = 51;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gender_ = "";
    /**
     * <code>optional string gender = 52;</code>
     */
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string gender = 52;</code>
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string gender = 52;</code>
     */
    public Builder setGender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string gender = 52;</code>
     */
    public Builder clearGender() {
      
      gender_ = getDefaultInstance().getGender();
      onChanged();
      return this;
    }
    /**
     * <code>optional string gender = 52;</code>
     */
    public Builder setGenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gender_ = value;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>optional int32 age = 53;</code>
     */
    public int getAge() {
      return age_;
    }
    /**
     * <code>optional int32 age = 53;</code>
     */
    public Builder setAge(int value) {
      
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 age = 53;</code>
     */
    public Builder clearAge() {
      
      age_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object country_ = "";
    /**
     * <code>optional string country = 54;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string country = 54;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string country = 54;</code>
     */
    public Builder setCountry(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      country_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string country = 54;</code>
     */
    public Builder clearCountry() {
      
      country_ = getDefaultInstance().getCountry();
      onChanged();
      return this;
    }
    /**
     * <code>optional string country = 54;</code>
     */
    public Builder setCountryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      country_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object province_ = "";
    /**
     * <code>optional string province = 55;</code>
     */
    public java.lang.String getProvince() {
      java.lang.Object ref = province_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        province_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string province = 55;</code>
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      java.lang.Object ref = province_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string province = 55;</code>
     */
    public Builder setProvince(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      province_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string province = 55;</code>
     */
    public Builder clearProvince() {
      
      province_ = getDefaultInstance().getProvince();
      onChanged();
      return this;
    }
    /**
     * <code>optional string province = 55;</code>
     */
    public Builder setProvinceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      province_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object city_ = "";
    /**
     * <code>optional string city = 56;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string city = 56;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string city = 56;</code>
     */
    public Builder setCity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      city_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string city = 56;</code>
     */
    public Builder clearCity() {
      
      city_ = getDefaultInstance().getCity();
      onChanged();
      return this;
    }
    /**
     * <code>optional string city = 56;</code>
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      city_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceType_ = "";
    /**
     * <pre>
     * ad info 竞价胜出的广告信息  （100-199）
     * </pre>
     *
     * <code>optional string source_type = 100;</code>
     */
    public java.lang.String getSourceType() {
      java.lang.Object ref = sourceType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ad info 竞价胜出的广告信息  （100-199）
     * </pre>
     *
     * <code>optional string source_type = 100;</code>
     */
    public com.google.protobuf.ByteString
        getSourceTypeBytes() {
      java.lang.Object ref = sourceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ad info 竞价胜出的广告信息  （100-199）
     * </pre>
     *
     * <code>optional string source_type = 100;</code>
     */
    public Builder setSourceType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ad info 竞价胜出的广告信息  （100-199）
     * </pre>
     *
     * <code>optional string source_type = 100;</code>
     */
    public Builder clearSourceType() {
      
      sourceType_ = getDefaultInstance().getSourceType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ad info 竞价胜出的广告信息  （100-199）
     * </pre>
     *
     * <code>optional string source_type = 100;</code>
     */
    public Builder setSourceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bidType_ = "";
    /**
     * <code>optional string bid_type = 101;</code>
     */
    public java.lang.String getBidType() {
      java.lang.Object ref = bidType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bidType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string bid_type = 101;</code>
     */
    public com.google.protobuf.ByteString
        getBidTypeBytes() {
      java.lang.Object ref = bidType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bidType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string bid_type = 101;</code>
     */
    public Builder setBidType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bidType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string bid_type = 101;</code>
     */
    public Builder clearBidType() {
      
      bidType_ = getDefaultInstance().getBidType();
      onChanged();
      return this;
    }
    /**
     * <code>optional string bid_type = 101;</code>
     */
    public Builder setBidTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bidType_ = value;
      onChanged();
      return this;
    }

    private long bidPrice_ ;
    /**
     * <pre>
     *出价
     * </pre>
     *
     * <code>optional int64 bid_price = 102;</code>
     */
    public long getBidPrice() {
      return bidPrice_;
    }
    /**
     * <pre>
     *出价
     * </pre>
     *
     * <code>optional int64 bid_price = 102;</code>
     */
    public Builder setBidPrice(long value) {
      
      bidPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *出价
     * </pre>
     *
     * <code>optional int64 bid_price = 102;</code>
     */
    public Builder clearBidPrice() {
      
      bidPrice_ = 0L;
      onChanged();
      return this;
    }

    private long posId_ ;
    /**
     * <pre>
     *广告位置
     * </pre>
     *
     * <code>optional int64 pos_id = 150;</code>
     */
    public long getPosId() {
      return posId_;
    }
    /**
     * <pre>
     *广告位置
     * </pre>
     *
     * <code>optional int64 pos_id = 150;</code>
     */
    public Builder setPosId(long value) {
      
      posId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广告位置
     * </pre>
     *
     * <code>optional int64 pos_id = 150;</code>
     */
    public Builder clearPosId() {
      
      posId_ = 0L;
      onChanged();
      return this;
    }

    private long accountId_ ;
    /**
     * <pre>
     *广告主
     * </pre>
     *
     * <code>optional int64 account_id = 151;</code>
     */
    public long getAccountId() {
      return accountId_;
    }
    /**
     * <pre>
     *广告主
     * </pre>
     *
     * <code>optional int64 account_id = 151;</code>
     */
    public Builder setAccountId(long value) {
      
      accountId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广告主
     * </pre>
     *
     * <code>optional int64 account_id = 151;</code>
     */
    public Builder clearAccountId() {
      
      accountId_ = 0L;
      onChanged();
      return this;
    }

    private long unitId_ ;
    /**
     * <pre>
     *广告单元
     * </pre>
     *
     * <code>optional int64 unit_id = 152;</code>
     */
    public long getUnitId() {
      return unitId_;
    }
    /**
     * <pre>
     *广告单元
     * </pre>
     *
     * <code>optional int64 unit_id = 152;</code>
     */
    public Builder setUnitId(long value) {
      
      unitId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广告单元
     * </pre>
     *
     * <code>optional int64 unit_id = 152;</code>
     */
    public Builder clearUnitId() {
      
      unitId_ = 0L;
      onChanged();
      return this;
    }

    private long creativeId_ ;
    /**
     * <pre>
     *广告创意
     * </pre>
     *
     * <code>optional int64 creative_id = 153;</code>
     */
    public long getCreativeId() {
      return creativeId_;
    }
    /**
     * <pre>
     *广告创意
     * </pre>
     *
     * <code>optional int64 creative_id = 153;</code>
     */
    public Builder setCreativeId(long value) {
      
      creativeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广告创意
     * </pre>
     *
     * <code>optional int64 creative_id = 153;</code>
     */
    public Builder clearCreativeId() {
      
      creativeId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object eventType_ = "";
    /**
     * <pre>
     * event
     * </pre>
     *
     * <code>optional string event_type = 200;</code>
     */
    public java.lang.String getEventType() {
      java.lang.Object ref = eventType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * event
     * </pre>
     *
     * <code>optional string event_type = 200;</code>
     */
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      java.lang.Object ref = eventType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * event
     * </pre>
     *
     * <code>optional string event_type = 200;</code>
     */
    public Builder setEventType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eventType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * event
     * </pre>
     *
     * <code>optional string event_type = 200;</code>
     */
    public Builder clearEventType() {
      
      eventType_ = getDefaultInstance().getEventType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * event
     * </pre>
     *
     * <code>optional string event_type = 200;</code>
     */
    public Builder setEventTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      eventType_ = value;
      onChanged();
      return this;
    }

    private long send_ ;
    /**
     * <pre>
     *广告下发了
     * </pre>
     *
     * <code>optional int64 send = 201;</code>
     */
    public long getSend() {
      return send_;
    }
    /**
     * <pre>
     *广告下发了
     * </pre>
     *
     * <code>optional int64 send = 201;</code>
     */
    public Builder setSend(long value) {
      
      send_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广告下发了
     * </pre>
     *
     * <code>optional int64 send = 201;</code>
     */
    public Builder clearSend() {
      
      send_ = 0L;
      onChanged();
      return this;
    }

    private long impression_ ;
    /**
     * <pre>
     *广告曝光了
     * </pre>
     *
     * <code>optional int64 impression = 202;</code>
     */
    public long getImpression() {
      return impression_;
    }
    /**
     * <pre>
     *广告曝光了
     * </pre>
     *
     * <code>optional int64 impression = 202;</code>
     */
    public Builder setImpression(long value) {
      
      impression_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广告曝光了
     * </pre>
     *
     * <code>optional int64 impression = 202;</code>
     */
    public Builder clearImpression() {
      
      impression_ = 0L;
      onChanged();
      return this;
    }

    private long click_ ;
    /**
     * <pre>
     *广告点击了
     * </pre>
     *
     * <code>optional int64 click = 203;</code>
     */
    public long getClick() {
      return click_;
    }
    /**
     * <pre>
     *广告点击了
     * </pre>
     *
     * <code>optional int64 click = 203;</code>
     */
    public Builder setClick(long value) {
      
      click_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广告点击了
     * </pre>
     *
     * <code>optional int64 click = 203;</code>
     */
    public Builder clearClick() {
      
      click_ = 0L;
      onChanged();
      return this;
    }

    private long download_ ;
    /**
     * <pre>
     *广告点击了
     * </pre>
     *
     * <code>optional int64 download = 204;</code>
     */
    public long getDownload() {
      return download_;
    }
    /**
     * <pre>
     *广告点击了
     * </pre>
     *
     * <code>optional int64 download = 204;</code>
     */
    public Builder setDownload(long value) {
      
      download_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广告点击了
     * </pre>
     *
     * <code>optional int64 download = 204;</code>
     */
    public Builder clearDownload() {
      
      download_ = 0L;
      onChanged();
      return this;
    }

    private long installed_ ;
    /**
     * <pre>
     *广告安装了
     * </pre>
     *
     * <code>optional int64 installed = 205;</code>
     */
    public long getInstalled() {
      return installed_;
    }
    /**
     * <pre>
     *广告安装了
     * </pre>
     *
     * <code>optional int64 installed = 205;</code>
     */
    public Builder setInstalled(long value) {
      
      installed_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广告安装了
     * </pre>
     *
     * <code>optional int64 installed = 205;</code>
     */
    public Builder clearInstalled() {
      
      installed_ = 0L;
      onChanged();
      return this;
    }

    private long pay_ ;
    /**
     * <pre>
     *广告支付了
     * </pre>
     *
     * <code>optional int64 pay = 206;</code>
     */
    public long getPay() {
      return pay_;
    }
    /**
     * <pre>
     *广告支付了
     * </pre>
     *
     * <code>optional int64 pay = 206;</code>
     */
    public Builder setPay(long value) {
      
      pay_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广告支付了
     * </pre>
     *
     * <code>optional int64 pay = 206;</code>
     */
    public Builder clearPay() {
      
      pay_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:grpc.AdLog)
  }

  // @@protoc_insertion_point(class_scope:grpc.AdLog)
  private static final com.lixl.stream.entity.AdLog DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lixl.stream.entity.AdLog();
  }

  public static com.lixl.stream.entity.AdLog getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdLog>
      PARSER = new com.google.protobuf.AbstractParser<AdLog>() {
    public AdLog parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdLog(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AdLog> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdLog> getParserForType() {
    return PARSER;
  }

  public com.lixl.stream.entity.AdLog getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

